server:
  port: 10086
spring:
  application:
    name: itcast-eureka # 将来作为微服务的名称注入到eureka容器
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  server:
    eviction-interval-timer-in-ms: 5000
